import type { Employee, Leave, Payslip, Attendance, PerformanceReview } from './types'

export const DEMO_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    employeeCode: 'EMP-001',
    firstName: 'Harshal',
    lastName: 'Ugale',
    email: 'founder@cloudaeon.com',
    phone: '+91 98765 00001',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Harshal&backgroundColor=b6e3f4',
    department: 'Executive',
    jobTitle: 'Founder & CEO',
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    startDate: '2020-01-01',
    basicSalary: 250000,
    hra: 100000,
    transport: 10000,
    pf: 21600,
    taxSlab: 30,
  },
  {
    id: 'emp-002',
    employeeCode: 'EMP-002',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'hr@cloudaeon.com',
    phone: '+91 98765 00002',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Priya&backgroundColor=c0aede',
    department: 'Human Resources',
    jobTitle: 'HR Director',
    role: 'HR',
    status: 'ACTIVE',
    startDate: '2020-03-15',
    managerId: 'emp-001',
    managerName: 'Harshal Ugale',
    basicSalary: 120000,
    hra: 48000,
    transport: 8000,
    pf: 14400,
    taxSlab: 20,
  },
  {
    id: 'emp-003',
    employeeCode: 'EMP-003',
    firstName: 'Rahul',
    lastName: 'Mehta',
    email: 'rahul@cloudaeon.com',
    phone: '+91 98765 00003',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Rahul&backgroundColor=d1d4f9',
    department: 'Engineering',
    jobTitle: 'Senior Software Engineer',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    startDate: '2021-06-01',
    managerId: 'emp-004',
    managerName: 'Neha Gupta',
    basicSalary: 95000,
    hra: 38000,
    transport: 6000,
    pf: 11400,
    taxSlab: 20,
  },
  {
    id: 'emp-004',
    employeeCode: 'EMP-004',
    firstName: 'Neha',
    lastName: 'Gupta',
    email: 'neha@cloudaeon.com',
    phone: '+91 98765 00004',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Neha&backgroundColor=ffd5dc',
    department: 'Product',
    jobTitle: 'Product Manager',
    role: 'MANAGER',
    status: 'ACTIVE',
    startDate: '2021-02-10',
    managerId: 'emp-001',
    managerName: 'Harshal Ugale',
    basicSalary: 115000,
    hra: 46000,
    transport: 7000,
    pf: 13800,
    taxSlab: 20,
  },
  {
    id: 'emp-005',
    employeeCode: 'EMP-005',
    firstName: 'Arjun',
    lastName: 'Singh',
    email: 'arjun@cloudaeon.com',
    phone: '+91 98765 00005',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Arjun&backgroundColor=b6e3f4',
    department: 'Engineering',
    jobTitle: 'Full Stack Developer',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    startDate: '2022-01-17',
    managerId: 'emp-004',
    managerName: 'Neha Gupta',
    basicSalary: 80000,
    hra: 32000,
    transport: 5000,
    pf: 9600,
    taxSlab: 10,
  },
  {
    id: 'emp-006',
    employeeCode: 'EMP-006',
    firstName: 'Deepika',
    lastName: 'Patel',
    email: 'deepika@cloudaeon.com',
    phone: '+91 98765 00006',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Deepika&backgroundColor=c0aede',
    department: 'Design',
    jobTitle: 'UI/UX Designer',
    role: 'EMPLOYEE',
    status: 'ON_LEAVE',
    startDate: '2022-03-21',
    managerId: 'emp-004',
    managerName: 'Neha Gupta',
    basicSalary: 75000,
    hra: 30000,
    transport: 5000,
    pf: 9000,
    taxSlab: 10,
  },
  {
    id: 'emp-007',
    employeeCode: 'EMP-007',
    firstName: 'Vikram',
    lastName: 'Joshi',
    email: 'vikram@cloudaeon.com',
    phone: '+91 98765 00007',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Vikram&backgroundColor=d1d4f9',
    department: 'Marketing',
    jobTitle: 'Marketing Director',
    role: 'MANAGER',
    status: 'ACTIVE',
    startDate: '2020-08-01',
    managerId: 'emp-001',
    managerName: 'Harshal Ugale',
    basicSalary: 110000,
    hra: 44000,
    transport: 7000,
    pf: 13200,
    taxSlab: 20,
  },
  {
    id: 'emp-008',
    employeeCode: 'EMP-008',
    firstName: 'Kavya',
    lastName: 'Nair',
    email: 'kavya@cloudaeon.com',
    phone: '+91 98765 00008',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Kavya&backgroundColor=ffd5dc',
    department: 'QA',
    jobTitle: 'QA Lead',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    startDate: '2021-09-06',
    managerId: 'emp-004',
    managerName: 'Neha Gupta',
    basicSalary: 70000,
    hra: 28000,
    transport: 5000,
    pf: 8400,
    taxSlab: 10,
  },
  {
    id: 'emp-009',
    employeeCode: 'EMP-009',
    firstName: 'Sanjay',
    lastName: 'Kumar',
    email: 'sanjay@cloudaeon.com',
    phone: '+91 98765 00009',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Sanjay&backgroundColor=b6e3f4',
    department: 'Engineering',
    jobTitle: 'DevOps Engineer',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    startDate: '2022-07-11',
    managerId: 'emp-004',
    managerName: 'Neha Gupta',
    basicSalary: 85000,
    hra: 34000,
    transport: 5000,
    pf: 10200,
    taxSlab: 10,
  },
  {
    id: 'emp-010',
    employeeCode: 'EMP-010',
    firstName: 'Ananya',
    lastName: 'Reddy',
    email: 'ananya@cloudaeon.com',
    phone: '+91 98765 00010',
    avatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Ananya&backgroundColor=c0aede',
    department: 'Operations',
    jobTitle: 'Business Analyst',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    startDate: '2023-01-02',
    managerId: 'emp-004',
    managerName: 'Neha Gupta',
    basicSalary: 65000,
    hra: 26000,
    transport: 4000,
    pf: 7800,
    taxSlab: 10,
  },
]

export const DEMO_LEAVES: Leave[] = [
  {
    id: 'lv-001',
    employeeId: 'emp-006',
    employeeName: 'Deepika Patel',
    employeeAvatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Deepika',
    department: 'Design',
    type: 'ANNUAL',
    startDate: '2025-05-05',
    endDate: '2025-05-10',
    days: 4,
    reason: 'Family vacation to Goa',
    status: 'APPROVED',
    approverId: 'emp-002',
    approverName: 'Priya Sharma',
    approvedAt: '2025-04-28',
    notes: 'Approved. Have a great vacation!',
    createdAt: '2025-04-25',
  },
  {
    id: 'lv-002',
    employeeId: 'emp-003',
    employeeName: 'Rahul Mehta',
    employeeAvatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Rahul',
    department: 'Engineering',
    type: 'SICK',
    startDate: '2025-05-08',
    endDate: '2025-05-08',
    days: 1,
    reason: 'Fever and cold',
    status: 'PENDING',
    createdAt: '2025-05-08',
  },
  {
    id: 'lv-003',
    employeeId: 'emp-005',
    employeeName: 'Arjun Singh',
    employeeAvatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Arjun',
    department: 'Engineering',
    type: 'ANNUAL',
    startDate: '2025-05-15',
    endDate: '2025-05-17',
    days: 3,
    reason: 'Personal work',
    status: 'PENDING',
    createdAt: '2025-05-07',
  },
  {
    id: 'lv-004',
    employeeId: 'emp-008',
    employeeName: 'Kavya Nair',
    employeeAvatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Kavya',
    department: 'QA',
    type: 'SICK',
    startDate: '2025-04-20',
    endDate: '2025-04-22',
    days: 3,
    reason: 'Viral fever',
    status: 'APPROVED',
    approverId: 'emp-002',
    approverName: 'Priya Sharma',
    approvedAt: '2025-04-19',
    createdAt: '2025-04-18',
  },
  {
    id: 'lv-005',
    employeeId: 'emp-009',
    employeeName: 'Sanjay Kumar',
    employeeAvatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Sanjay',
    department: 'Engineering',
    type: 'EMERGENCY',
    startDate: '2025-04-10',
    endDate: '2025-04-11',
    days: 2,
    reason: 'Medical emergency in family',
    status: 'APPROVED',
    approverId: 'emp-002',
    approverName: 'Priya Sharma',
    approvedAt: '2025-04-10',
    createdAt: '2025-04-10',
  },
  {
    id: 'lv-006',
    employeeId: 'emp-010',
    employeeName: 'Ananya Reddy',
    employeeAvatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Ananya',
    department: 'Operations',
    type: 'ANNUAL',
    startDate: '2025-05-20',
    endDate: '2025-05-23',
    days: 4,
    reason: 'Wedding ceremony',
    status: 'PENDING',
    createdAt: '2025-05-06',
  },
  {
    id: 'lv-007',
    employeeId: 'emp-007',
    employeeName: 'Vikram Joshi',
    employeeAvatar: 'https://api.dicebear.com/8.x/avataaars/svg?seed=Vikram',
    department: 'Marketing',
    type: 'COMPENSATORY',
    startDate: '2025-04-30',
    endDate: '2025-04-30',
    days: 1,
    reason: 'Worked on Sunday for product launch',
    status: 'APPROVED',
    approverId: 'emp-001',
    approverName: 'Harshal Ugale',
    approvedAt: '2025-04-29',
    createdAt: '2025-04-28',
  },
]

export const generatePayslips = (): Payslip[] => {
  const months = [1, 2, 3, 4, 5]
  const year = 2025
  const slips: Payslip[] = []

  DEMO_EMPLOYEES.forEach((emp) => {
    months.forEach((month) => {
      const grossPay = emp.basicSalary + emp.hra + emp.transport
      const pf = Math.round(emp.basicSalary * 0.12)
      const tax = Math.round(((grossPay - pf) * emp.taxSlab) / 100)
      const deductions = pf + tax
      const netPay = grossPay - deductions
      slips.push({
        id: `ps-${emp.id}-${year}-${month}`,
        employeeId: emp.id,
        employeeName: `${emp.firstName} ${emp.lastName}`,
        month,
        year,
        basicSalary: emp.basicSalary,
        hra: emp.hra,
        transport: emp.transport,
        grossPay,
        pf,
        tax,
        deductions,
        netPay,
        paidOn: month < 5 ? `${year}-${String(month).padStart(2, '0')}-28` : undefined,
      })
    })
  })

  return slips
}

export const DEMO_PAYSLIPS = generatePayslips()

export const generateAttendance = (employeeId: string): Attendance[] => {
  const records: Attendance[] = []
  const now = new Date('2025-05-08')
  const start = new Date('2025-04-01')
  const curr = new Date(start)

  while (curr <= now) {
    const day = curr.getDay()
    const dateStr = curr.toISOString().split('T')[0]

    if (day === 0 || day === 6) {
      records.push({ id: `att-${employeeId}-${dateStr}`, employeeId, date: dateStr, status: 'WEEKEND' })
    } else {
      const rand = Math.random()
      if (rand > 0.05) {
        records.push({
          id: `att-${employeeId}-${dateStr}`,
          employeeId,
          date: dateStr,
          checkIn: '09:' + String(Math.floor(Math.random() * 30)).padStart(2, '0'),
          checkOut: '18:' + String(Math.floor(Math.random() * 30)).padStart(2, '0'),
          status: 'PRESENT',
          hoursWorked: 8 + Math.random() * 2,
        })
      } else {
        records.push({ id: `att-${employeeId}-${dateStr}`, employeeId, date: dateStr, status: 'ABSENT' })
      }
    }

    curr.setDate(curr.getDate() + 1)
  }

  return records
}

export const DEMO_PERFORMANCE: PerformanceReview[] = [
  {
    id: 'pr-001',
    employeeId: 'emp-003',
    quarter: 'Q1',
    year: 2025,
    overallScore: 87,
    technicalSkills: 90,
    communication: 82,
    teamwork: 88,
    leadership: 75,
    delivery: 92,
    innovation: 85,
    reviewedBy: 'Neha Gupta',
    comments: 'Exceptional delivery this quarter. Should focus on leadership skills.',
    createdAt: '2025-04-01',
  },
  {
    id: 'pr-002',
    employeeId: 'emp-003',
    quarter: 'Q4',
    year: 2024,
    overallScore: 82,
    technicalSkills: 88,
    communication: 78,
    teamwork: 85,
    leadership: 70,
    delivery: 88,
    innovation: 80,
    reviewedBy: 'Neha Gupta',
    comments: 'Good performance. Needs to work on cross-team communication.',
    createdAt: '2024-12-28',
  },
  {
    id: 'pr-003',
    employeeId: 'emp-005',
    quarter: 'Q1',
    year: 2025,
    overallScore: 79,
    technicalSkills: 82,
    communication: 75,
    teamwork: 83,
    leadership: 68,
    delivery: 80,
    innovation: 88,
    reviewedBy: 'Neha Gupta',
    comments: 'Good technical skills, great innovation. Work on delivery timelines.',
    createdAt: '2025-04-01',
  },
  {
    id: 'pr-004',
    employeeId: 'emp-008',
    quarter: 'Q1',
    year: 2025,
    overallScore: 91,
    technicalSkills: 93,
    communication: 88,
    teamwork: 92,
    leadership: 85,
    delivery: 95,
    innovation: 82,
    reviewedBy: 'Neha Gupta',
    comments: 'Outstanding performance. Top performer this quarter.',
    createdAt: '2025-04-01',
  },
]

export const LEAVE_TREND_DATA = [
  { month: 'Jan', annual: 8, sick: 5, emergency: 2, other: 1 },
  { month: 'Feb', annual: 12, sick: 8, emergency: 1, other: 2 },
  { month: 'Mar', annual: 15, sick: 4, emergency: 3, other: 0 },
  { month: 'Apr', annual: 10, sick: 6, emergency: 2, other: 3 },
  { month: 'May', annual: 7, sick: 3, emergency: 1, other: 0 },
]

export const LEAVE_TYPE_DISTRIBUTION = [
  { name: 'Annual', value: 52, color: '#3b82f6' },
  { name: 'Sick', value: 26, color: '#ef4444' },
  { name: 'Emergency', value: 9, color: '#f97316' },
  { name: 'Compensatory', value: 7, color: '#8b5cf6' },
  { name: 'Unpaid', value: 3, color: '#6b7280' },
  { name: 'Maternity/Paternity', value: 3, color: '#ec4899' },
]

export const PERFORMANCE_TREND_DATA = [
  { quarter: 'Q2 2024', avg: 76 },
  { quarter: 'Q3 2024', avg: 79 },
  { quarter: 'Q4 2024', avg: 82 },
  { quarter: 'Q1 2025', avg: 85 },
]

export const DEPARTMENTS = ['Engineering', 'Human Resources', 'Product', 'Design', 'Marketing', 'QA', 'Operations', 'Executive', 'Finance']

export const DEMO_CREDENTIALS = [
  { role: 'Founder / CEO', email: 'founder@cloudaeon.com', password: 'demo123', empId: 'emp-001' },
  { role: 'HR Director', email: 'hr@cloudaeon.com', password: 'demo123', empId: 'emp-002' },
  { role: 'Employee (Rahul)', email: 'rahul@cloudaeon.com', password: 'demo123', empId: 'emp-003' },
]
